# Generated by Django 3.0.3 on 2020-08-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('certificate', models.CharField(max_length=5)),
                ('runtime', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('trailer', models.CharField(max_length=1000)),
            ],
        ),
    ]
